= {product} - Historias de Usuario
Universidad Católica Boliviana. <flavio.mirandaucb.edu.bo>
:product: BOT
## Introducción
El presente documento contiene el detalle de las historias de usuario para la construcción de un BOT de atención a estudiantes y docentes de la Universidad Católica Boliviana.
Se ha establecido que la funcionalidad mínima para la implementación será:
Para los estudiantes:

 1. Los estudiantes deben identificarse con el Bot mediante su cedula de identidad y la clave del sistema académico
 
 
 2. Los estudiantes pueden consultar su horario y materias mediante el Bot
 
 3. Los estudiantes pueden consultar y acceder a la información para ponerse en contacto con una determinada materia.
 
 4. Los estudiantes pueden solicitar un permiso mediante un justificativo 
 
 5. Los estudiantes pueden acceder a su información de saldos dentro de la universidad mediante el Bot
 
 Para los docentes:
 
 1. Los docentes deben identificarse con el Bot mediante su cedula de identidad y la clave del sistema académico 
 
 2. Los docentes pueden revisar su horario y aulas asignadas.
 
 3. Acceder a un listado de sus alumnos en cada clase.
 
 4. Los docentes deben poder autorizar o rechazar las vacaciones solicitadas.
 
 5. El personal de RRHH debe poder autorizar o rechazar las vacaciones solicitadas.


## Historias de Usuario.

### 002 - Consulta de horario y materias (estudiantes).

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*: 07/03/2022

*Prioridad*: ALTA

#### 002.1 Descripción

Un estudiante debe solicitar su información de horarios y materias mediante el Bot, para esto debe enviar las siglas de su materia o simplemente solicitar al Bot todo el horario. Una vez enviada la solicitud y la sigla el Bot obtendrá la información respectiva, para esto el estudiante deberá enviar la información de la siguiente manera:  

 * Las siglas de la materia (Para obtener la información de una materia en específico) o la palabra "horario" para mostrar todo el horario.

Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante

El diagrama de secuencia para la consulta será:
[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]
....
@startuml
actor Estudiante
Estudiante -> BOT: Solicitar Información de horarios y aulas
BOT --> Estudiante: Ingresar siglas de la materia
Estudiante --> BOT: Siglas de la materia
Bot --> estudiante: 

@enduml
....

#### Escenarios
1. Validación de datos introducidos por el estudiante.
2. Consulta incorrecta.
3. Consulta correcta.

#### 002.3 Casos de Prueba

 *Validación de datos introducidos por el estudiante* 

Descripción: Al momento de enviar las siglas de la materia, el Bot debe asegurarse de que esta exista o que el estudiante este registrado en esta ya que un estudiante que no está registrado en una materia no debería de poder ver la información de esta.
Pasos:

 1. El estudiante Ingresa y se identifica con el BOT vía Telegram y enviar el comando /Consulta_horarios_estudiantes
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "Debe ingresar las siglas de una materia valida"
2. El estudiante ingresa las siglas de una materia valida y en la que está registrado
    - Datos: Sis 101 (materia valida y registrada)
    - Resultado: El BOT consulta las siglas de la materia en la base de datos y envía los datos obtenidos al estudiante 
 3. El estudiante` coloca un espacio en blanco
    - Datos: Coloca `un espacio en blanco`
    - Resultado: El BOT pide nuevamente las siglas de la materia.
 4. El estudiante ingresa las siglas de una materia valida pero en la que no está registrado.
    - Datos:  `arq222`
    - Resultado: El Bot indica que no puede mostrar información de materias en las que el estudiante no está registrado.

