[#_bot_universidad__historias_de_usuario]
= {product} - Historias de Usuario
Universidad Católica Boliviana "San Pablo". <moises.valda@ucb.edu.bo>
v1.0
:product: BOT UNIVERSIDAD

== Introducción

Este documento describe en detalle las historias de usuario para la construcción de un Bot para, estudiantes o personal de la universidad.

Las funcionalidad son las siguientes:


    1. Identificacion de usuarios y acceso al sistema en funcion a estos.
    
Para Estudiantes:

    1. Consultar su horario.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos.

Para Docentes:

    1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno.

== Historias de Usuario

### 1 - Identificación de usuario

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*:07/03/2022

*Prioridad*: Muy alta


#### 1.1 Descripción
Para poder usar el Bot un usuario debe identificarse como estudiante o docente de la Universidad Católica Boliviana, para ello el usuario deberá proporcionar la siguiente información

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

Con esta información se realizará una consulta en la base de datos y de acuerdo a los resultados se le dará acceso al Bot.


El diagrama de secuencia para este proceso será:

[plantuml, format="png", id="Identificacion"]
....
@startuml
Actor: Usuario
Usuario --> BOT: Ingresa Ci y contraseña
Usuario --> BOT:
@enduml
....

#### 1.2 Escenarios

1. Usuario no registrados, los datos son incorrectos.
2. Usuario registrado, datos de estudiante correctos.
2. Usuario registrado, datos de docente correctos.


#### 1.3 Casos de Prueba

 *Usuario no registrado* 

Descripción: El Bot debe verificar la información y en caso de ser incorrecta no se debería mostrar ningún menú.

* Validación de parámetros* 
Descripción: Al momento de identificarse es necesario que el usuario ingrese su ci y contraseña para poder acceder
En caso de que el usuario no ingrese su información correctamente no se le otorgara acceso



 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: ninguno.
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese su ci y contraseña"
2. El usuario un espacio en blanco
    - Datos: espacio en blanco
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes"
2. El usuario ingresa Ci y contraseña incorrectos
    - Datos: Ci y contraseña incorrectos
    - Resultado: El BOT retorna un mensaje. "Datos incorrectos, verifique"
 3. El usuario ingresa Ci  incorrecto
    - Datos: Ci equivocado
    - Resultado: El BOT retorna un mensaje. "Ci no registrado, verifique"
 4. El usuario ingresa contraseña incorrecta
    - Datos: Contraseña incorrecta
    - Resultado: El BOT retorna un mensaje. "su contraseña es incorrecta, verifique"

### 2 - Consulta de horario (Estudiante)

Autor: Moises Carlos Valda Gutierrez

Fecha:07/03/2022

Prioridad: Alta


#### Descripción
Un estudiante debe solicitar su información de horarios y materias mediante el Bot, para esto debe enviar las siglas de su materia o simplemente solicitar al Bot todo el horario. Una vez enviada la solicitud y la sigla el Bot obtendrá la información respectiva, para esto el estudiante deberá enviar la información de la siguiente manera:

* Las siglas de la materia (Para obtener la información de una materia en específico)


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


El diagrama de secuencia para la consulta será:
[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]
....
@startuml
actor Estudiante
Estudiante -> BOT: Solicitar Información de horarios y aulas
BOT --> Estudiante: Ingresar siglas de la materia
Estudiante --> BOT: Siglas de la materia
Bot --> estudiante:

@enduml
....


### Escenarios

1. Siglas de la materia incorrectas o estudiante no registrado.
3. Datos correctos.

### Casos de Prueba

Siglas de la materia incorrectas

Descripción: El Bot debe validar la informacion ingresada por el estudiante y verificar que esta sea correcta ademas revisar si el estudiate esta registrado en esta ya que un estudiante que no está registrado en una materia no debería de poder ver la información de esta.


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta_horarios_estudiantes
- Datos: NINGUNO.
- Resultado esperado: El BOT retorna un mensaje. "Ingrese las siglas de su materia".

2. El `Estudiante` coloca un espacio en blanco
- Datos: ¨  ¨
- Resultado: El BOT retorna un mensaje. "Debe ingresar sus datos".

3. El `Estudiante` coloca un espacio en blanco
- Datos: ¨  ¨
- Resultado: El BOT pide nuevamente las siglas de la materia.

3. El `Estudiante` un emoji y un simbolo de dolar
- Datos: ¨:3 $  ¨
- Resultado:  El BOT retorna un mensaje. "No se aceptan caracteres especiales".

4. El estudiante ingresa las siglas de una materia inexistente o incorrecta.
- Datos:  `arq666`
- Resultado:   El BOT retorna un mensaje. "Materia inexistente".

4. El estudiante ingresa las siglas de una materia valida pero en la que no está registrado.
- Datos:  `arq222`
- Resultado: El Bot indica que no puede mostrar información de materias en las que el estudiante no está registrado.



== Historias de Usuario

### 3 - Consulta Estado de Cuenta

*Autor*: Mauro Moya

*Fecha*:08/03/2022

*Prioridad*: Muy alta


#### 1.1 Descripción
Una Vez validada la información del estudiante y seleccionado la opcion de consulta de deuda

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

* Cuenta para obtener el estado de cuenta del  estudiante


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


El diagrama de secuencia para la consulta será:
[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]
....
@startuml
actor Estudiante
Estudiante -> BOT: Solicitar Información cuenta
Bot --> estudiante: su cuenta hasta la fecha es:
Numero-Cuota-monto-FechaLimite

@enduml
....


### Escenarios

1. Cuenta con deuda
2. Cuenta con Sin deuda

### Casos de Prueba

Cuenta con deuda o sin deuda

Descripción: El Bot una vez validado la informacion ingresada por el estudiante y solicitando cuenta mostrara sus deudas o sin deudas


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta cuenta, en el caso con deuda

- Resultado esperado: El BOT retorna un mensaje tiene deuda y muestra-> 
Numero-Cuota-monto-FechaLimite

2. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta cuenta, en el caso sin deuda

- Resultado esperado: El BOT retorna un mensaje Puede estar Feliz sin deuda alguna


== Historias de Usuario

### 4 - Consulta Notas

*Autor*: Mauro Moya

*Fecha*:08/03/2022

*Prioridad*: Muy alta


#### 1.1 Descripción
Una Vez validada la información del estudiante y seleccionado la opcion de consulta de deuda

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

* Para obtener las notas


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


El diagrama de secuencia para la consulta será:
[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]
....
@startuml
actor Estudiante
Estudiante -> BOT: Solicitar Información notas
Bot --> estudiante: actual o semestre "1-2022"
Estudiante -> BOT: actual
Bot --> estudiante: tus notas actuales son: Materia-Nota Parcial-Nota Final
@enduml
....


### Escenarios

1. Notas Actuales.
3. Notas Semestre.

### Casos de Prueba

Notas

Descripción: El Bot una vez validado la informacion ingresada por el estudiante y solicitando notas indicara actual o semestral


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta notas, el BOT preguntara actual o semestral, en caso de actual

- Resultado esperado: El BOT retorna un mensaje Sus notas actuales-> 
Materia-Nota Parcial-Nota Final

2. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta notas, el BOT preguntara actual o semestral, en caso de actual

- Resultado esperado: El BOT retorna un mensaje Sus notas del semestre"1-2022"-> 
Materia-Nota Parcial-Nota Final