[#_bot_universidad__historias_de_usuario]
= {product} - Historias de Usuario
Universidad Católica Boliviana "San Pablo". <moises.valda@ucb.edu.bo>
v1.0
:product: BOT UNIVERSIDAD

== Introducción

Este documento describe en detalle las historias de usuario para la construcción de un Bot para, estudiantes o personal de la universidad.

Las funcionalidad son las siguientes:


    1. Identificacion de usuarios y acceso al sistema en funcion a estos.
    
Para Estudiantes:

    1. Consultar su horario.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos.

Para Docentes:

    1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno.

== Historias de Usuario

### 1 - Identificación de usuario

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*:07/03/2022

*Prioridad*: Muy alta


#### 1.1 Descripción
Para poder usar el Bot un usuario debe identificarse como estudiante o docente de la Universidad Católica Boliviana, para ello el usuario deberá proporcionar la siguiente información

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

Con esta información se realizará una consulta en la base de datos y de acuerdo a los resultados se le dará acceso al Bot.


El diagrama de secuencia para este proceso será:

[plantuml, format="png", id="Identificacion"]
....
@startuml
Actor: Usuario
Usuario --> BOT: Ingresa Ci y contraseña
Usuario --> BOT:
@enduml
....

#### 1.2 Escenarios

1. Usuario no registrados, los datos son incorrectos.
2. Usuario registrado, datos de estudiante correctos.
2. Usuario registrado, datos de docente correctos.


#### 1.3 Casos de Prueba

 *Usuario no registrado* 

Descripción: El Bot debe verificar la información y en caso de ser incorrecta no se debería mostrar ningún menú.

* Validación de parámetros* 
Descripción: Al momento de identificarse es necesario que el usuario ingrese su ci y contraseña para poder acceder
En caso de que el usuario no ingrese su información correctamente no se le otorgara acceso



 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: ninguno.
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese su ci y contraseña"
2. El usuario un espacio en blanco
    - Datos: espacio en blanco
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes"
2. El usuario ingresa Ci y contraseña incorrectos
    - Datos: Ci y contraseña incorrectos
    - Resultado: El BOT retorna un mensaje. "Datos incorrectos, verifique"
 3. El usuario ingresa Ci  incorrecto
    - Datos: Ci equivocado
    - Resultado: El BOT retorna un mensaje. "Ci no registrado, verifique"
 4. El usuario ingresa contraseña incorrecta
    - Datos: Contraseña incorrecta
    - Resultado: El BOT retorna un mensaje. "su contraseña es incorrecta, verifique"
    
