[#_bot_universidad__historias_de_usuario]
= {product} - Historias de Usuario
Universidad Católica Boliviana "San Pablo". <moises.valda@ucb.edu.bo>
v1.0
:product: BOT UNIVERSIDAD

== Introducción

Este documento describe en detalle las historias de usuario para la construcción de un Bot para, estudiantes o personal de la universidad.

Las funcionalidad son las siguientes:


    1. Identificacion de usuarios.
    2. Acceso al sistema en funcion a los usuarios.
    
Para Estudiantes:

    1. Consultar su horario.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos.

Para Docentes:

    1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno.

== Historias de Usuario



*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*:07/03/2022

*Prioridad*: Alta

### 1 - Identificación de usuario

#### 1.1 Descripción
Para poder usar el Bot un usuario debe identificarse como estudiante o docente de la Universidad Católica Boliviana, para ello el usuario deberá proporcionar la siguiente información

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

Con esta información se realizará una consulta en la base de datos y de acuerdo a los resultados se le dará acceso al Bot.


El diagrama de secuencia para este proceso será:

[plantuml, format="png", id="Identificacion"]
....
@startuml
Actor: Usuario
Usuario --> BOT: Ingresa Ci y contraseña
Usuario --> BOT:
@enduml
....

#### 1.2 Escenarios

1. Usuario no registrados, los datos son incorrectos.
2. Usuario registrado, datos de estudiante correctos.
2. Usuario registrado, datos de docente correctos.


#### 1.3 Casos de Prueba

 *Usuario no registrado* 

Descripción: El Bot debe verificar la información y en caso de ser incorrecta no se debería mostrar ningún menú.

* Validación de parámetros* 
Descripción: Al momento de identificarse es necesario que el usuario ingrese su ci y contraseña para poder acceder
En caso de que el usuario no ingrese su información correctamente no se le otorgara acceso



 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: ninguno.
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese su ci y contraseña"
2. El usuario un espacio en blanco
    - Datos: espacio en blanco
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes"
2. El usuario ingresa Ci y contraseña incorrectos
    - Datos: Ci y contraseña incorrectos
    - Resultado: El BOT retorna un mensaje. "Datos incorrectos, verifique"
 3. El usuario ingresa Ci  incorrecto
    - Datos: Ci equivocado
    - Resultado: El BOT retorna un mensaje. "Ci no registrado, verifique"
 4. El usuario ingresa contraseña incorrecta
    - Datos: Contraseña incorrecta
    - Resultado: El BOT retorna un mensaje. "su contraseña es incorrecta, verifique"
    



*Autor*: Moises Carlos Valda Gutierrez

*Fecha*:07/03/2022

*Prioridad*: Alta

### 2 - Consulta de horario (Estudiante)

#### Descripción
Yo como `Estudiante` necesito conocer mis horarios semestrales, para esto necesito estar inscrito a una o más materias en el actual semestre. Es importante que el bot pueda notificar lo siguiente:

    * Cantidad de materías inscritas.
    * El Horario con todas las materias isncritas.

La consulta tendrá los siguientes estados:

*_Realizada_*: El usuario realiza la consulta de sus horarios.

*_Rechazada_*: Debido a que el estudiante no está inscrito al semestre actual, no puede consultar horarios.

*_Aceptada_*: Consulta aceptada ya que cumple los requisitos anteriores (estar inscrito al semestre actual, comando ingresado correctamente).

Diagrama de estado para la `consulta de horarios` es:

[plantuml,format="png", id="Estados_Consulta"]
....
@startuml

state c <<choice>>

Realizada --> c
c --> Aceptada : [Cumple]
c --> Rechazada : [No Cumple]
Rechazada -->[*]
Aceptada -->Muestra_Horario
Muestra_Horario -->[*]
@enduml
....

### Escenarios

    1. Validación de datos introducidos por el estudiante.

    2. Consulta Incorrecta.

    3. Consulta Correcta.

### Casos de Prueba

*Validación de datos introducidos por el estudiante*

_Descripción_: El Bot debe asegurarse de que  el estudiante esté inscrito a las materias para poder así obtener los horarios. Este proceso es verificando si el comando _Consulta_horarios_estudiante_ es validado. También es necesario verificar que los datos del usuario sean de un estudiante:

_Pasos_:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta_horarios_estudiantes
- Datos: NINGUNO.
- Resultado esperado: El BOT retorna un mensaje. "Debe ingresar un comando válido".

2. El `Estudiante` coloca un espacio en blanco
- Datos: Coloca `un espacio en blanco`
- Resultado: El BOT pide nuevamente que ingrese el comando.


*Consulta Incorrecta*

_Descripción_: Al momento de realizar alguna consulta por un estudiante, es importante que el BOT verifique que la materia exista o que el estudiante esté inscrito en la materia.

_Pasos_:

    1. El estudiante se identifica con el BOT, ingresa y envía el comando:
    - /Consulta_horarios_estud
    - Resultado: El Bot Retorna "Debe Ingresar un comando válido"

    2. El estudiante ingresa el comando:
    - /Consulta_horarios_estudiantes
    - El BOT verifica que el estudiante no está inscrito a alguna materia.

    3. El estudiante ingresa una sigla de materia:
    - SIS-000
    - El Bot responde: "Materia Inexistente".

*Consulta Correcta*

_Descripción_: El Estudiante ingresa datos validos, como ser el comando para consultar horarios, el Bot veririca los datos correctos y da una respuesta  dependiendo el caso.

_Pasos_:

    1. El estudiante se identifica con el BOT, e ingresa y envía el comando:
    - /Consulta_horarios_estudiante
    - Resultado: El Bot verifica los datos correctos y responde mostrando los horarios correspondientes.

