[#_bot_universidad__historias_de_usuario]
= {product} - Historias de Usuario
Universidad Católica Boliviana "San Pablo". <moises.valda@ucb.edu.bo>
v1.0
:product: BOT UNIVERSIDAD

== Introducción

Este documento describe en detalle las historias de usuario para la construcción de un Bot para, estudiantes o personal de la universidad.

Las funcionalidad son las siguientes:


    1. Autenticación de usuarios y acceso al sistema en funcion a estos.
    
Para Estudiantes:

    1. Consultar su horario.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos.

Para Docentes:

    1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno.

== Historias de Usuario

### 1 - Autenticación de usuario

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*:07/03/2022

*Prioridad*: Muy alta


#### 1.1 Descripción
Para poder usar el Bot un usuario debe autenticarse como estudiante o docente de la Universidad Católica Boliviana, para ello el usuario deberá proporcionar la siguiente información

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

Con esta información se realizará una consulta en la base de datos y de acuerdo a los resultados se le dará acceso al Bot.


El diagrama de secuencia para este proceso será:

[plantuml, format="png", id="Identificacion"]
....
@startuml
actor Usuario #Yellow

Usuario -[#red]> BOT: Solicitar Informacion del usuario
BOT -[#blue]-> Estudiante: 'Ingrese su Ci'
Usuario -[#red]> BOT: Ingresar Ci
BOT -[#blue]-> Usuario: 'Ingrese Contraseña'
Usuario -[#red]> BOT: Ingresar contraseña

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de los datos del usuario'
BBDD -[#green]-> BOT: 'Envía respuesta a solicitud'
BOT -[#blue]-> Estudiante: 'Verifica la informacion y notifica al usuario'


@enduml

....
#### 1.2 Escenarios

1. Usuario no registrados, los datos son incorrectos.
2. Usuario registrado, datos de estudiante correctos.
3. Usuario registrado, datos de docente correctos.


#### 1.3 Casos de Prueba

 *Usuario no registrado* 

Descripción: El Bot debe verificar la información y en caso de ser incorrecta no se debería mostrar ningún menú.

* Validación de parámetros* 
Descripción: Al momento de identificarse es necesario que el usuario ingrese su ci y contraseña para poder acceder
En caso de que el usuario no ingrese su información correctamente no se le otorgara acceso



 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: ninguno.
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese un el comando correcto".
2. El usuario ingresa un espacio en blanco
    - Datos: ¨  ¨.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes".
3. El usuario ingresa un Ci incorrecto
    - Datos: Ci no registrado.
    - Resultado: El BOT retorna un mensaje. "Datos incorrectos, verifique".
 2. El usuario ingresa un emoji y un símbolo de exclamación
    - Datos: ¨:) ! ¨.
    - Resultado: El BOT retorna un mensaje. "No puede ingresar caracteres especiales"   
 4. El usuario ingresa un Ci correcto
    - Datos: Ci. 
    - Resultado: El BOT retorna un mensaje. "Ingrese su contraseña(la misma que eb sistema academico)".
 5.  El usuario ingresa un emoji
    - Datos: :3.
    - Resultado: El BOT retorna un mensaje. "No puede ingresar emoijs como datos".
 6.  El `Estudiante` ingresa datos en blanco o incorrectos más de
     5 veces.
     - *Datos:*  `  `
     - *Resultado esperado:* El Bot retorna: 'Usted no puede realizar más consultas, siguiente intento en "4 horas, 59 minutos, 59 segundos" y elimina los mensajes anteriores.'   
 7. El usuario ingresa una contraseña correcta
    - Datos: contraseña. 
    - Resultado: El BOT muestra el menu de opciones.(de acuerdo al tipo de usuario) y elimina los mensajes anteriores.


*Usuario registrado, datos de estudiante correctos*


Descripción: Luego de registrarse el bot debe mostrar el menu respectivo.

* Validación de parámetros* 
Descripción: Al momento de identificarse el Bot identifica el tipo de usuario y en funcion a esto, en caso de ser de tipo estudiante, muestra el menu de opciones respectivas.


1. El usuario ingresa al bot y se Autentica correctamente
    - Resultado esperado: El BOT muestra el menu de opciones para estudiantes. 
    "1. Consultar su horario y aulas asiganadas.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos."

*Usuario registrado, datos de docente correctos*


Descripción: Luego de registrarse el bot debe mostrar el menu respectivo.

* Validación de parámetros* 
Descripción: Al momento de identificarse el Bot identifica el tipo de usuario y en funcion a esto, en caso de ser de tipo docentee, muestra las opciones de1 docente.


1. El usuario ingresa al bot y se Autentica correctamente
    - Resultado esperado: El BOT muestra el menu de opciones para docentes. 
    "1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno."






### 2 - Consulta de horario (Estudiante)

*Autor:* Moises Carlos Valda Gutierrez

*Fecha:* 09/03/2022

*Prioridad:* Alta


#### Descripción

Un `Estudiante` debe poder solicitar la información de `horarios` o `materias` mediante el BOT, para esto el estudiante debe enviar la siguiente información:

    * Las siglas de la materia _(Para obtener la información de una materia en específico)_ o simplemente solicitar al BOT el horario completo. 
    
Una vez enviada la solicitud  con la sigla de la materia o el comando para conocer el horario correspondiente, el BOT obtendrá la información respectiva, realizando una consulta a la `Base de Datos` y retornará dando una respuesta a la solicitud del estudiante.

*Solicitar Información de Materia:*

En el siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_materia"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: Solicitar Información de materia
BOT -[#blue]-> Estudiante: 'Ingrese siglas de la materia'
Estudiante -[#red]> BOT: Ingresa siglas de la materia

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de la materia'
BBDD -[#green]-> BOT: 'Envía respuesta a solicitud'
BOT -[#blue]-> Estudiante: ' Muestra información de la Materia'


@enduml

....

*Solicitar Horario:*

En el siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: Solicitar Horario
BOT -[#blue]-> Estudiante: 'Ingrese Comando específico'
Estudiante -[#red]> BOT: Ingresa: /ConsultarHorario

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta'
BBDD -[#green]-> BOT: 'Devuelve resultado de la consulta'
BOT -[#blue]-> Estudiante: ' Genera y muestra el Horario'

@enduml

....


=== Escenarios

    1. Estudiante ingresa siglas o comando incorrectos.
    2. Estudiante no se encuentra registrado.
    3. Estudiante se encuentra registrado.
    4. Estudiante ingresa datos correctos.

### Casos de Prueba

*10.1.1 Estudiante ingresa siglas o comando incorrectos.*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante` y verificar que sea correcta. Cabe recalcar que no existe diferencia a la hora de realizar una búsqueda con mayúsculas o minúsculas.

*_Pasos a seguir:_*

1. El `Estudiante` ingresa, se identifica con el `BOT` vía Telegram y envía el comando:
 
- */Consulta_horarios_estud....*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Ingrese comando correcto".

2. El `Estudiante` ingresa un espacio en blanco
- *Datos:* ¨  ¨
- *Resultado esperado:* El BOT retorna un mensaje: "Por favor Ingrese Datos".

3. El `Estudiante` ingresa un emoji y un símbolo de dólar
- *Datos:* ¨:3 $  ¨
- *Resultado esperado:*  El BOT retorna un mensaje: "No se aceptan caracteres especiales".

4. El `Estudiante` ingresa las siglas de una materia inexistente o incorrecta.
- *Datos:*  `arq666`
- *Resultado esperado:*   El BOT retorna un mensaje: "Materia inexistente".

5. El `Estudiante` ingresa las siglas de una materia válida, en la que no se encuentra registrado.
- *Datos:*  `arq222`
- *Resultado esperado:* El Bot retorna: 'No se puede mostrar información de materias en las que el estudiante no se encuentra registrado.'

6. El `Estudiante` ingresa datos en blanco o incorrectos más de 5 veces.
- *Datos:*  `arq45644564`
- *Resultado esperado:* El Bot retorna: 'Usted no puede realizar más consultas, siguiente intento en "4 horas, 59 minutos, 59 segundos".'

*10.1.2 Estudiante no se encuentra registrado*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante` y verificar que el estudiante se encuentre registrado. Si no se encuentra registrado, no puede proceder a pedir información requerida.

*_Pasos a seguir:_*

1. El `Estudiante` ingresa, se comunica con el `BOT` vía Telegram y envía el comando:
 
- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Usted no se encuentra registrado, por favor ingrese el comando /registrarme para comenzar el proceso de registro".

*10.1.3 Estudiante se encuentra registrado*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante` y verificar que el estudiante se encuentre registrado.

*_Pasos a seguir:_*

1. El `Estudiante` se encuentra registrado, ingresa, se comunica con el `BOT` vía Telegram y envía el comando:
 
- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "¿Qué necesita?".

*10.1.4 Estudiante ingresa datos correctos*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante`.

*_Pasos a seguir:_*

1. El `Estudiante` ingresa las siglas de una materia válida, independientemente de Mayúsculas o Minúsculas.

- *Datos:* "SIs-213"
- *Resultado esperado:* El BOT retorna un mensaje: "Los detalles de la materia son los siguientes: 'Martes 13:30-15:15, 'Aula:' D15 y Jueves 18:45-21:15', 'Aula:' D15".

2. El `Estudiante` ingresa el comando para consultar su horario.
- */Consulta_horarios_estudiante*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Su horario es el siguiente: _'Muestra Horario_' ".



== Historias de Usuario

### 3 - Consulta Estado de Cuenta

*Autor*: Mauro Moya

*Fecha*:08/03/2022

*Prioridad*: Muy alta


#### 3.1 Descripción
Un *Estudiante* podra consultar el estado de su cuenta por medio del *BOT* de telegram, para esto previa validacion del estudiante y seleccionado la opcion de consulta de deuda. El *BOT* debe llevar un control de: * El estado de cuenta del estudiante a la fecha * Los dias de retrazo del pago de la deuda.

La consulta pasará por los siguientes estados:

- *Con Deuda:* Cuando el estudiante consulta su deuda al BOT, y el BOT muestra su deuda.
- *No tiene Deuda:* Cuando el estudiante consulta su deuda al BOT, y el BOT responde que no tiene deuda.


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


El diagrama de estados para la *Consulta* será:
[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]
....
@startuml
[*] --> CONSULTA
CONSULTA --> DEUDA
DEUDA --> [*]
CONSULTA -> SIN_DEUDA
SIN_DEUDA --> [*]
@enduml
....

### Escenarios

1. Cuenta con deuda
2. Cuenta con Sin deuda

### Casos de Prueba

Cuenta con deuda o sin deuda

Descripción: El Bot una vez validado la informacion ingresada por el estudiante y solicitando cuenta mostrara sus deudas o sin deudas


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando:

 -/Consulta cuenta

*- Resultado esperado*: El BOT retorna un mensaje tiene deuda y muestra:

 -Numero-Cuota-monto-FechaLimite-DiasRetraso

2. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando:

 -/Consulta cuenta

*- Resultado esperado*: El BOT retorna un mensaje tiene deuda y muestra:

 -NO TIENE DEUDA

*Consulta Deuda:*

El en siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: consulta deuda
BOT -[#blue]-> Estudiante: 'Ingrese Comando específico'
Estudiante -[#red]> BOT: Ingresa: /ConsultarDeuda

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de la deuda'
BBDD -[#green]-> BOT: 'Devuelve resultado de la consulta'
BOT -[#blue]-> Estudiante: ' Genera y muestra la deuda'

@enduml

....


== Historias de Usuario

### 4 - Consulta Notas

*Autor*: Mauro Moya

*Fecha*:10/03/2022

*Prioridad*: Muy alta


#### 4.1 Descripción
Un *Estudiante* podra consultar sus notas por medio del *BOT* de telegram, para esto previa validacion del estudiante y escribiendo el comando de /consulta notas, el *BOT* el bot respondera *actuales o *semestre 


* Para obtener las notas


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


*Consulta Notas:*

El en siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: consulta deuda
BOT -[#blue]-> Estudiante: 'Ingrese Comando específico'
Estudiante -[#red]> BOT: Ingresa: /ConsultarDeuda
BOT -[#blue]-> Estudiante: 'Ingrese el comando /Actual o el semestre en formado l: 1-2020'
database BBDD #brown

Estudiante -[#red]> BOT: Ingresa: /Actual o el comando /1-2020

BOT -[#green]-> BBDD: 'Realiza consulta de notas'
BBDD -[#green]-> BOT: 'Devuelve resultado de las notas'
BOT -[#blue]-> Estudiante: ' Genera y muestra la deuda'

@enduml

....


### 4.2 Escenarios

1. Notas Actuales.
2. Notas Semestre.

### 4.3 Casos de Prueba


Descripción: El Bot una vez validado la informacion ingresada por el estudiante y solicitando notas indicara actual o semestral


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando:

 -Estudiante: /Consulta notas
 BOT: Ingrese comando actual o semestral ejemplo 1-2022

- Resultado esperado: El BOT retorna un mensaje Sus notas actuales-> 
Materia-Nota Parcial-Nota Final

2. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta notas, el BOT preguntara actual o semestral, en caso de actual

- Resultado esperado: El BOT retorna un mensaje Sus notas del semestre"1-2022"-> 
Materia-Nota Parcial-Nota Final

