[#_bot_universidad__historias_de_usuario]
= {product} - Historias de Usuario
Universidad Católica Boliviana "San Pablo". <moises.valda@ucb.edu.bo>
<mauro.moya@ucb.edu.bo>
v1.0
:product: BOT UNIVERSIDAD

== 1 Introducción

Este documento describe en detalle las historias de usuario para la construcción de un Bot para, estudiantes o personal de la universidad.

Las funcionalidad son las siguientes:


    1. Autenticación de usuarios y acceso al sistema en funcion a estos.
    
Para Estudiantes:

    1. Consultar su horario.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos.

Para Docentes:

    1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno.



### 2 - Autenticación de usuario

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*:07/03/2022

*Prioridad*: Muy alta


#### 2.1 Descripción
Para poder usar el Bot un usuario debe autenticarse como estudiante o docente de la Universidad Católica Boliviana, para ello el usuario deberá proporcionar la siguiente información

    * Cédula de identidad.
    * Contraseña (La misma que en el sistema académico).

Con esta información se realizará una consulta en la base de datos y de acuerdo a los resultados se le dará acceso al Bot.


El diagrama de secuencia para este proceso será:

[plantuml, format="png", id="Identificacion"]
....
@startuml
actor Usuario #Yellow

Usuario -[#red]> BOT: Solicitar Informacion del usuario
BOT -[#blue]-> Estudiante: 'Ingrese su Ci'
Usuario -[#red]> BOT: Ingresar Ci
BOT -[#blue]-> Usuario: 'Ingrese Contraseña'
Usuario -[#red]> BOT: Ingresar contraseña

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de los datos del usuario'
BBDD -[#green]-> BOT: 'Envía respuesta a solicitud'
BOT -[#blue]-> Estudiante: 'Verifica la informacion y notifica al usuario'


@enduml

....
#### 2.2 Escenarios

1. Usuario no registrados, los datos son incorrectos.
2. Usuario registrado, datos de estudiante correctos.
3. Usuario registrado, datos de docente correctos.


#### 2.3 Casos de Prueba

 *Usuario no registrado* 

Descripción: El Bot debe verificar la información y en caso de ser incorrecta no se debería mostrar ningún menú.

* Validación de parámetros* 
Descripción: Al momento de identificarse es necesario que el usuario ingrese su ci y contraseña para poder acceder
En caso de que el usuario no ingrese su información correctamente no se le otorgara acceso



 1. Ingresar al BOT via Telegram y enviar el comando /start
    - Datos: ninguno.
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese un el comando correcto".
2. El usuario ingresa un espacio en blanco
    - Datos: ¨  ¨.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes".
3. El usuario ingresa un Ci incorrecto
    - Datos: Ci no registrado.
    - Resultado: El BOT retorna un mensaje. "Datos incorrectos, verifique".
 2. El usuario ingresa un emoji y un símbolo de exclamación
    - Datos: ¨:) ! ¨.
    - Resultado: El BOT retorna un mensaje. "No puede ingresar caracteres especiales"   
 4. El usuario ingresa un Ci correcto
    - Datos: Ci. 
    - Resultado: El BOT retorna un mensaje. "Ingrese su contraseña(la misma que eb sistema academico)".
 5.  El usuario ingresa un emoji
    - Datos: :3.
    - Resultado: El BOT retorna un mensaje. "No puede ingresar emoijs como datos".
 6.  El `Estudiante` ingresa datos en blanco o incorrectos más de
     5 veces.
     - *Datos:*  `  `
     - *Resultado esperado:* El Bot retorna: 'Usted no puede realizar más consultas, siguiente intento en "4 horas, 59 minutos, 59 segundos" y elimina los mensajes anteriores.'   
 7. El usuario ingresa una contraseña correcta
    - Datos: contraseña. 
    - Resultado: El BOT muestra el menu de opciones.(de acuerdo al tipo de usuario) y elimina los mensajes anteriores.


#### 2.4 Usuario registrado, datos de estudiante correctos


Descripción: Luego de registrarse el bot debe mostrar el menu respectivo.

* Validación de parámetros* 
Descripción: Al momento de identificarse el Bot identifica el tipo de usuario y en funcion a esto, en caso de ser de tipo estudiante, muestra el menu de opciones respectivas.


1. El usuario ingresa al bot y se Autentica correctamente
    - Resultado esperado: El BOT muestra el menu de opciones para estudiantes. 
    "1. Consultar su horario y aulas asiganadas.
    2. Consultar el detalle por materia (enlaces).
    3. Consultar el estado de cuenta.
    4. Consultar notas.
    5. Solicitar permisos con adjuntos."

#### 2.5 Usuario registrado, datos de docente correctos


Descripción: Luego de registrarse el bot debe mostrar el menu respectivo.

* Validación de parámetros* 
Descripción: Al momento de identificarse el Bot identifica el tipo de usuario y en funcion a esto, en caso de ser de tipo docentee, muestra las opciones de1 docente.


1. El usuario ingresa al bot y se Autentica correctamente
    - Resultado esperado: El BOT muestra el menu de opciones para docentes. 
    "1. Consultar su horario y aulas asignadas.
    2. Consultar el listado de alumnos por clase.
    3. Aprobar o rechazar solicitudes de permiso.
    4. Subir notas por materia, uno a uno."






### 3 - Consulta de horario (Estudiante)

*Autor:* Moises Carlos Valda Gutierrez

*Fecha:* 09/03/2022

*Prioridad:* Alta


#### 3.1 Descripción

Un `Estudiante` debe poder solicitar la información de `horarios` o `materias` mediante el BOT, para esto el estudiante debe enviar la siguiente información:

    * Las siglas de la materia _(Para obtener la información de una materia en específico)_ o simplemente solicitar al BOT el horario completo. 
    
Una vez enviada la solicitud  con la sigla de la materia o el comando para conocer el horario correspondiente, el BOT obtendrá la información respectiva, realizando una consulta a la `Base de Datos` y retornará dando una respuesta a la solicitud del estudiante.

*Solicitar Información de Materia:*

En el siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_materia"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: /start
BOT -[#blue]-> Estudiante: '¿Qué desea?'
Estudiante -[#red]> BOT: Solicitar Información de materia
BOT -[#blue]-> Estudiante: 'Ingrese siglas de la materia'
Estudiante -[#red]> BOT: Ingresa siglas de la materia

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de la materia'
BBDD -[#green]-> BOT: 'Envía respuesta a solicitud'
BOT -[#blue]-> Estudiante: ' Muestra información de la Materia'


@enduml

....

*Solicitar Horario:*

En el siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: /start
BOT -[#blue]-> Estudiante: '¿Qué desea?'
Estudiante -[#red]> BOT: Solicitar Horario
BOT -[#blue]-> Estudiante: 'Ingrese Comando específico'
Estudiante -[#red]> BOT: Ingresa: /ConsultarHorario

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta'
BBDD -[#green]-> BOT: 'Devuelve resultado de la consulta'
BOT -[#blue]-> Estudiante: ' Genera y muestra el Horario'

@enduml

....


=== 3.2 Escenarios

    1. Estudiante ingresa siglas o comando incorrectos.
    2. Estudiante no se encuentra registrado.
    3. Estudiante se encuentra registrado.
    4. Estudiante ingresa datos correctos.

### 3.4 Casos de Prueba

*Estudiante ingresa siglas o comando incorrectos.*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante` y verificar que sea correcta. Cabe recalcar que no existe diferencia a la hora de realizar una búsqueda con mayúsculas o minúsculas.

*_Pasos a seguir:_*

1. El `Estudiante` ingresa, se identifica con el `BOT` vía Telegram y envía el comando:
 
- */Consulta_horarios_estud....*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Ingrese comando correcto".

2. El `Estudiante` ingresa un espacio en blanco
- *Datos:* ¨  ¨
- *Resultado esperado:* El BOT retorna un mensaje: "Por favor Ingrese Datos".

3. El `Estudiante` ingresa un emoji y un símbolo de dólar
- *Datos:* ¨:3 $  ¨
- *Resultado esperado:*  El BOT retorna un mensaje: "No se aceptan caracteres especiales".

4. El `Estudiante` ingresa las siglas de una materia inexistente o incorrecta.
- *Datos:*  `arq666`
- *Resultado esperado:*   El BOT retorna un mensaje: "Materia inexistente".

5. El `Estudiante` ingresa las siglas de una materia válida, en la que no se encuentra registrado.
- *Datos:*  `arq222`
- *Resultado esperado:* El Bot retorna: 'No se puede mostrar información de materias en las que el estudiante no se encuentra registrado.'

6. El `Estudiante` ingresa datos en blanco o incorrectos más de 5 veces.
- *Datos:*  `arq45644564`
- *Resultado esperado:* El Bot retorna: 'Usted no puede realizar más consultas, siguiente intento en "4 horas, 59 minutos, 59 segundos".'

#### 3.4.1 Estudiante no se encuentra registrado

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante` y verificar que el estudiante se encuentre registrado. Si no se encuentra registrado, no puede proceder a pedir información requerida.

*_Pasos a seguir:_*

1. El `Estudiante` ingresa, se comunica con el `BOT` vía Telegram y envía el comando:
 
- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Usted no se encuentra registrado, por favor ingrese el comando /registrarme para comenzar el proceso de registro".

#### 3.4.2 Estudiante se encuentra registrado*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante` y verificar que el estudiante se encuentre registrado.

*_Pasos a seguir:_*

1. El `Estudiante` se encuentra registrado, ingresa, se comunica con el `BOT` vía Telegram y envía el comando:
 
- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "¿Qué necesita?".

*10.1.4 Estudiante ingresa datos correctos*

*_Descripción:_* El Bot debe validar la información ingresada por el `Estudiante`.

*_Pasos a seguir:_*

1. El `Estudiante` ingresa las siglas de una materia válida, independientemente de Mayúsculas o Minúsculas.

- *Datos:* "SIs213"
- *Resultado esperado:* El BOT retorna un mensaje: "Los detalles de la materia son los siguientes: 'Martes 13:30-15:15, 'Aula:' D15 y Jueves 18:45-21:15', 'Aula:' D15".

2. El `Estudiante` ingresa el comando para consultar su horario.
- */horarios*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Su horario es el siguiente: _'Muestra Horario_' ".



### 4 - Consulta Estado de Cuenta

*Autor*: Mauro Moya

*Fecha*:08/03/2022

*Prioridad*: Muy alta


#### 4.1 Descripción
Un *Estudiante* podra consultar el estado de su cuenta por medio del *BOT* de telegram, para esto previa validacion del estudiante y seleccionado la opcion de consulta de deuda. El *BOT* debe llevar un control de: * El estado de cuenta del estudiante a la fecha * Los dias de retrazo del pago de la deuda.

La consulta pasará por los siguientes estados:

- *Con Deuda:* Cuando el estudiante consulta su deuda al BOT, y el BOT muestra su deuda.
- *No tiene Deuda:* Cuando el estudiante consulta su deuda al BOT, y el BOT responde que no tiene deuda.


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


El diagrama de estados para la *Consulta* será:
[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]
....
@startuml
[*] --> CONSULTA
CONSULTA --> DEUDA
DEUDA --> [*]
CONSULTA -> SIN_DEUDA
SIN_DEUDA --> [*]
@enduml
....

### 4.2 Escenarios

1. Cuenta con deuda
2. Cuenta con Sin deuda

### 4.3 Casos de Prueba

Cuenta con deuda o sin deuda

Descripción: El Bot una vez validado la informacion ingresada por el estudiante y solicitando cuenta mostrara sus deudas o sin deudas


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando:

 -/cuenta

*- Resultado esperado*: El BOT retorna un mensaje tiene deuda y muestra:

 -Numero-Cuota-monto-FechaLimite-DiasRetraso

2. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando:

 -/cuenta

*- Resultado esperado*: El BOT retorna un mensaje tiene deuda y muestra:

 -NO TIENE DEUDA

*Consulta Deuda:*

El en siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: consulta deuda
BOT -[#blue]-> Estudiante: 'Ingrese Comando específico'
Estudiante -[#red]> BOT: Ingresa: /ConsultarDeuda

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de la deuda'
BBDD -[#green]-> BOT: 'Devuelve resultado de la consulta'
BOT -[#blue]-> Estudiante: ' Genera y muestra la deuda'

@enduml

....


### 5 - Consulta Notas

*Autor*: Mauro Moya

*Fecha*:10/03/2022

*Prioridad*: Muy alta


#### 5.1 Descripción
Un *Estudiante* podra consultar sus notas por medio del *BOT* de telegram, para esto previa validacion del estudiante y escribiendo el comando de /notas, el *BOT* el bot respondera *actuales o *semestre 


* Para obtener las notas


Con esta información se realizara una consulta en la base de datos y se mostraran los resultados al estudiante


*Consulta Notas:*

El en siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Estudiante #Yellow

Estudiante -[#red]> BOT: consulta deuda
BOT -[#blue]-> Estudiante: 'Ingrese Comando específico'
Estudiante -[#red]> BOT: Ingresa: /ConsultarDeuda
BOT -[#blue]-> Estudiante: 'Ingrese el comando /Actual o el semestre en formado l: 1-2020'
database BBDD #brown

Estudiante -[#red]> BOT: Ingresa: /Actual o el comando /1-2020

BOT -[#green]-> BBDD: 'Realiza consulta de notas'
BBDD -[#green]-> BOT: 'Devuelve resultado de las notas'
BOT -[#blue]-> Estudiante: ' Genera y muestra la deuda'

@enduml

....


#### 5.2 Escenarios

1. Notas Actuales.
2. Notas Semestre.

#### 5.3 Casos de Prueba


Descripción: El Bot una vez validado la informacion ingresada por el estudiante y solicitando notas indicara actual o semestral


Pasos:

1. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando:

 -Estudiante: /notas
 BOT: Ingrese comando actual o semestral ejemplo 1-2022

- Resultado esperado: El BOT retorna un mensaje Sus notas actuales-> 
Materia-Nota Parcial-Nota Final

2. El estudiante Ingresa y se identifica con el BOT vía Telegram y envía el comando /Consulta notas, el BOT preguntara actual o semestral, en caso de actual

- Resultado esperado: El BOT retorna un mensaje Sus notas del semestre"1-2022"-> 
Materia-Nota Parcial-Nota Final


### 6 - Solicitar permisos con adjuntos.

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*: 10/03/2022

*Prioridad*:  Alta


#### 6.1 Descripción
Un estudiante puede solicitar permisos para ausentarse a un docente mediante el Bot, para esto debe enviar el motivo de su falta ademas de una imagen adjunta de un justificativo, una vez enviada la solicitud, el docente procederá a autorizar o rechazar el permiso, hecho esto el Bot notificará al estudiante el resultado. 

La solicitud del estudiante pasara por los siguientes estados:

 * *SOLICITADO*: Cuando el estudiante envía su solicitud al BOT y es validada por este.
  * *NO VÁLIDO*: Cuando el estudiante envía su solicitud al BOT y no cumple con los requisitos.
  * *APROBADO*: Solicitud aprobada por el docente
  * *RECHAZADO*: Solicitud rechazada por el docente

El diagrama de estados para la `SOLICITUD` será:
[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> SOLICITADO
SOLICITADO --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADO -> APROBADO
SOLICITADO -> RECHAZADO
RECHAZADO --> [*]
@enduml
....

6.2 Escenarios

1. El estudiante emite la solicitud.
2. El estudiante recibe los resultados de su solicitud.
3. La solicitud esta caducada


#### 6.3 Casos de Prueba

 *El estudiante emite la solicitud.* 

Descripción: 
Al momento de realizar la solicitud es necesario que el estudiante identifique la fecha y la materia a la que solicitara el permiso y posteriormente ingresar la informacion respectiva  y en caso de no cumplir con los requisitos el Bot no debe dejar que la solicitud sea emitida, en caso de que la solicitud sea exitosa esta se guarda en la base de datos con un código

1. El estudiante Ingresa y se autentifica con el BOT vía Telegram y envía el comando:
    -/Enviarsolicitud
    - Resultado esperado: El BOT retorna un mensaje. ¨Ingrese la fecha de su permiso en el formato dd/mm/aa¨.
2. El estudiante ingresa un espacio en blanco
    - Datos: ¨  ¨.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes".
3. El estudiante ingresa los datos en el formato incorrecto
    - Datos: 103222.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos en el formato dd/mm/aa".
4. El estudiante ingresa una fecha no valida
    - Datos: 65/16/516.
    - Resultado: El BOT retorna un mensaje. "debe ingresar una fecha valida.
5. El usuario ingresa la fecha correspondiente
    - Datos: 10/03/2022
    - Resultado: El Bot solicitara al estudiante que ingrese las siglas de la materia.
6. El usuario ingresa la materia correspondiente
    - Datos: Sis 211
    - Resultado: El Bot solicitara al estudiante que ingrese un mensaja los motivos de su falta.
 7. El estudiante ingresa un espacio en blanc o
    - Datos: ¨  ¨.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes"."   
 8. El estudiante ingresa los motivos de su falta
    - Resultado: El BOT Solicita al estudiante un justificativo en formato jpg o pdf.
 9.  El estudiante envia un video/audio
    - Datos: : hola.mp3.
    - Resultado: El BOT retorna un mensaje. "Solo puede Enviar datos en formato jpg o pdf".
 10.  El estudiante ingresa el justificativo correspondiente
     - Datos: : justificativo.pfd.
     - Resultado esperado: El Bot retorna 'Solicitud registrada" y notifica al docente.  



*El estudiante recibe los resultados de su solicitud.*

Descripción: Una vez que el docente responde la solicitud del estudiante este debe ser notificado mediante el Bot.


1. El estudiante estudiante esta autentificado en el BOT vía Telegram y este le envia una notificación.
    - Resultado esperado: El BOT retorna un mensaje. ¨Su solicitud en la materia sis 111 tiene una respuesta:¨ y muestra el resultado del docente acompañado de una recomendación de este si existiera.

### 7 - Consulta de horario y aulas (DOCENTE)

*Autor:* Moises Carlos Valda Gutierrez

*Fecha:* 12/03/2022

*Prioridad:* Muy Alta


#### 7.1 Descripción

Un `Docente` debe poder solicitar la información de `horarios` o `materias` mediante el BOT, para este proceso el docente debe enviar la siguiente información:

* Las siglas de la materia _(Para obtener la información de una materia y la asignación de aula correspondiente)_ o simplemente solicitar al BOT el horario completo.

Una vez enviada la solicitud  con la sigla de la materia o el comando para conocer el horario correspondiente, el BOT obtendrá la información respectiva, realizando una consulta a la `Base de Datos`, donde se encuentra almacenada toda la información, una vez realizada la consulta el `BOT` retornará dando una respuesta a la solicitud del docente.

*Solicitar Información de Materia:*

En el siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_materia"]

....

@startuml

actor Docente #Blue

Docente -[#red]> BOT: /start
BOT -[#blue]-> Docente: '¿Qué desea?'
Docente -[#red]> BOT: Solicitar Información de materia
BOT -[#blue]-> Docente: 'Ingrese siglas de la materia'
Docente -[#red]> BOT: Ingresa siglas de la materia

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta de la materia'
BBDD -[#green]-> BOT: 'Envía respuesta a solicitud'
BOT -[#blue]-> Docente: 'Muestra información de la Materia'


@enduml

....

*Solicitar Horario:*

En el siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_docente"]

....

@startuml

actor Docente #Blue

Docente -[#red]> BOT: /start
BOT -[#blue]-> Docente: '¿Qué desea?'
Docente -[#red]> BOT: Solicitar Horario
BOT -[#blue]-> Docente: 'Ingrese Comando específico'
Docente -[#red]> BOT: /ConsultarHorarioDocente

database BBDD #brown

BOT -[#green]-> BBDD: 'Realiza consulta'
BBDD -[#green]-> BOT: 'Información requerida '
BOT -[#blue]-> Docente: 'Genera y muestra el Horario'

@enduml

....


=== 7.2 Escenarios

1. Docente ingresa siglas o comando incorrectos.
2. Docente no se encuentra registrado.
3. Docente se encuentra registrado.
4. Docente ingresa datos correctos.

### 7.3 Casos de Prueba

#### 7.3.1 Docente ingresa siglas o comando incorrectos.*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente` y verificar que sea correcta. Cabe recalcar que no existe diferencia a la hora de realizar una búsqueda con mayúsculas o minúsculas.

*_Pasos a seguir:_*

1. El `Docente` ingresa, se identifica con el `BOT` vía Telegram y envía el comando:

- */horarios*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Ingrese comando correcto".

2. El `Docente` ingresa un espacio en blanco
- *Datos:* ¨  ¨
- *Resultado esperado:* El BOT retorna un mensaje: "Por favor Ingrese Datos".

3. El `Docente` ingresa caracteres especiales
- *Datos:* ¨:3 $  ¨
- *Resultado esperado:*  El BOT retorna un mensaje: "No se aceptan caracteres especiales".

4. El `Docente` ingresa las siglas de una materia inexistente o incorrecta.
- *Datos:*  `arq666`
- *Resultado esperado:*   El BOT retorna un mensaje: "Materia inexistente".

5. El `Docente` ingresa las siglas de una materia válida, en la que no se encuentra registrado.
- *Datos:*  `arq222`
- *Resultado esperado:* El Bot retorna: 'La información de esta materia no le corresponde a usted'

6. El `Docente` ingresa datos en blanco o incorrectos más de 5 veces.
- *Datos:*  `arq45644564`
- *Resultado esperado:* El Bot retorna: 'Usted no puede realizar más consultas, siguiente intento en "4 horas, 59 minutos, 59 segundos".'

#### 7.3.2 Docente no se encuentra registrado*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente` y verificar que se encuentre registrado. Si no se encuentra registrado, no puede proceder a pedir la información requerida.

*_Pasos a seguir:_*

1. El `Docente` ingresa, se comunica con el `BOT` vía Telegram y envía el comando:

- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Usted no se encuentra registrado, por favor ingrese el comando /registrarme para comenzar el proceso de registro".

#### 7.3.3 Docente se encuentra registrado*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente` y verificar que el estudiante se encuentre registrado.

*_Pasos a seguir:_*

1. El `Docente` se encuentra registrado, ingresa, se comunica con el `BOT` vía Telegram y envía el comando:

- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "¿Qué necesita?".

#### 7.3.4 Docente ingresa datos correctos*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente`.

*_Pasos a seguir:_*

1. El `Docente` ingresa las siglas de una materia válida, independientemente de Mayúsculas o Minúsculas.

- *Datos:* "SIs213"
- *Resultado esperado:* El BOT retorna un mensaje: "Los detalles de la materia son los siguientes: 'Martes 13:30-15:15, 'Aula:' D15 y Jueves 18:45-21:15', 'Aula:' D15".

2. El `Docente` ingresa el comando para consultar su horario.
- */Consulta_horarios_docente*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Su horario es el siguiente: _'Muestra Horario_' ".

### 8 Consultar listado de Alumnos por clase

*Autores*: Moises Carlos Valda Gutiérrez -
Mauro Moya

*Fecha*: 15/03/2022

*Prioridad*: Alta

#### 8.1 Descripción
El `Docente` puede realizar una consulta al BOT para conocer el listado de los alumnos por clase o materia, para este proceso el docente debe enviar la siguiente información:

* Enviar el comando /ConsultarAlumnos
* Sigla de la Materia-Paralelo


El diagrama de secuencia para esta Historia es el siguiente:


[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Docente #Blue

Docente -[#red]> BOT: Comando Erroneo
BOT -[#blue]-> Docente: 'Ingrese Comando específico'
Docente -[#red]> BOT: Ingresa: /ConsultarAlumnos
BOT -[#blue]-> Docente: 'Ingrese el comando /SIGLA-PARALELO: EJ: MAT224-1'
Docente -[#red]> BOT: Comando Erroneo
BOT -[#blue]-> Docente: 'Ingrese Comando específico'
database BBDD #brown

Docente -[#red]> BOT: Ingresa: /MAT224-1

BOT -[#green]-> BBDD: 'Realiza consulta de alumnos'
BBDD -[#green]-> BOT: 'Devuelve resultado de las alumnos de la materia y paralelo'
BOT -[#blue]-> Docente: ' muestra el listado de alumnos:'

@enduml

....

#### 8.2 Escenarios
1. Docente no se encuentra registrado.
2. Docente ingresa comando no válido.
3. Docente ingresa comando válido.

#### 8.3 Casos de Prueba

#### 8.3.1 Docente no se encuentra registrado.*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente` y verificar que dicho docente se encuentre registrado, en caso de no estar registrado no puede proceder a solicitar información específica.

*_Pasos a seguir:_*

1. El `Docente` ingresa, se comunica con el `BOT` vía Telegram y envía el comando:

- */start*
- *Datos:* NINGUNO.
- *Resultado esperado:* El BOT retorna un mensaje: "Usted no se encuentra registrado, por favor ingrese el comando /registrarme para comenzar el proceso de registro".

#### 8.3.2 Docente ingresa comando no válido.*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente` y verificar que esta información sea correcta para poder responder a la solicitud de manera efectiva.

*_Pasos a seguir:_*

1. El `Docente` ingresa, se identifica con el `BOT` vía Telegram y envía el comando:

- */start
- *Resultado esperado:* ¿Qué necesita?
- */SolicitarLi....*
- *Resultado esperado:* El BOT retorna un mensaje: "Ingrese comando correcto".

2. El `Docente` ingresa un espacio en blanco
- *Datos:* ¨  ¨
- *Resultado esperado:* El BOT retorna un mensaje: "Por favor Ingrese Datos".

3. El `Docente` ingresa datos en blanco o incorrectos más de 5 veces.
- *Datos:*  `/Solidaddddd`
- *Resultado esperado:* El Bot retorna: 'Usted no puede realizar más consultas, siguiente intento en "4 horas, 59 minutos, 59 segundos".'


#### 8.3.3 Docente ingresa comando válido.*

*_Descripción:_* El Bot debe validar la información ingresada por el `Docente` y verificar que esta información sea correcta para poder responder a la solicitud de manera efectiva. Cabe mencionar que la consulta es independiente de ingresar mayúsculas o minúsculas

*_Pasos a seguir:_*

1. El `Docente` ingresa, se identifica con el `BOT` vía Telegram y envía el comando:

 -Docente: /ConsultaAlumnos
 -BOT: Ingrese el comando /SIGLA-PARALELO: EJ: MAT224-1
 -Docente: /SIS224-1
 -BOT: En la materia de Ingenieria del Software Paralelo 1 pertecen los siguientes Estudiantes:
 1) Moises Valda
 2) Gabriel Miranda
 3) Mauro Moya

### 9 - Aprobar o rechazar solicitudes de permiso.

*Autor*: Flavio Gabriel Miranda Velarde

*Fecha*: 10/03/2022

*Prioridad*:  Alta


#### 9.1 Descripción
Un docente puede otorgar permisos a los estudiantes para ausentarse mediante el bot, para esto el docente recibe una notificacion con los sigueintes datos:

-La fecha para el permiso
-Un mensaje del estudiante con los motivos de su falta.
-Un archivo jpg o pdf con el justificativo

La solicitud del estudiante puede tener los siguientes resultados
 * *PENDIENTE*: Cuando la solicitud valida aun no fue revisada por el docente.
  * *RESPONDIDA*: Solicitud revisada por el docente
  * *CADUCADA*: Solicitud caducadae

El diagrama de estados para la `SOLICITUD` será:
[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> PENDIENTE
PENDIENTE -> RESPONDIDA
PENDIENTE -> CADUCADA
CADUCADA --> [*]
@enduml
....

#### 9.2 Escenarios

1. Solicitud respondida.
2. Solicitud caducada.


#### 9.3 Casos de Prueba

 *Solicitud respondida* 

Descripción: 
Luego de que la informacion pertinente es mostrada al docente por medio del Bot este debe de proporcionar una respuesta a esta seguida de un mensaje en caso de que el docente lo desee.

1. El docente esta autentificado en el BOT vía Telegram y este le envia una notificación.
    - Resultado esperado: El BOT muestra un mensaje. ¨Tiene una nueva solicitud del estudiante Juan Perez en la materia Sis 111, ingrese a la pestaña de solicitudes de permisos para responder¨.
2. El docente Ingresa el comando /solicitudes
    - Resultado: El BOT Le muestra al docente todas las solicitudes pendientes con sus datos respectivos sguidos del texto ¨Ingrese el código de una solicitud¨. 
3.  El docente ingresa un espacio en blanco
    - Datos: ¨  ¨.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes"." 
4. El docente ingresa un código inexistente
    - Datos: 6461651.
    - Resultado: El BOT retorna un mensaje. "debe ingresar un código valido"
5. El docente ingresa un código valido
    - Datos: 122
    - Resultado: El Bot mostrará al docente el motivo del permiso y el justificativo del estudiante seguidos del texto "ingrese 'aprobar'o'rechazar'".
6. El docente ingresa una palabra incorrecta
    - Datos: hola
    - Resultado: El Bot solicitará una respuesta al docente con el texto "ingrese 'aprobar'o'rechazar'".
 7. El docente ingresa "aprobar"
    - Datos: "aprobar".
    - Resultado: El BOT retorna un mensaje. "solicitud aprobada, se notificará al estudiante"   
 8. El docente ingresa "rechazar"
    - Datos: "rechazar".
    - Resultado: El BOT retorna un mensaje. "solicitud rechazada, se notificará al estudiante"





*solicitud caducada*

Descripción: Una vez que la fecha de una solicitud se ha vencido el Bot emite una notificación al docente indicandole que la solicitud ha vencido y que debe de responder a esta lo antes posible.



1. El docente esta autentificado en el BOT vía Telegram y este le envia una notificación.
    - Resultado esperado: El BOT muestra un mensaje. ¨La solicitud del estudiante Juan Perez en la fecha 10/0382022 ha caducado, responda a esta lo antes posible¨.
2. El docente Ingresa el comando /solicitudes
    - Resultado: El BOT Le muestra al docente todas las solicitudes pendientes con sus datos respectivos, tomando como prioridad las solicitudes mas antiguas, seguidos del texto ¨Ingrese el código de una solicitud¨. 
3.  El docente ingresa un espacio en blanco
    - Datos: ¨  ¨.
    - Resultado: El BOT retorna un mensaje. "debe ingresar los datos correspondientes"." 
4. El docente ingresa un código inexistente
    - Datos: 6461651.
    - Resultado: El BOT retorna un mensaje. "debe ingresar un código valido"
5. El docente ingresa un código valido
    - Datos: 122
    - Resultado: El Bot mostrará al docente el motivo del permiso y el justificativo del estudiante seguidos del texto "ingrese 'aprobar'o'rechazar'".
6. El docente ingresa una palabra incorrecta
    - Datos: hola
    - Resultado: El Bot solicitará una respuesta al docente con el texto "ingrese 'aprobar'o'rechazar'".
 7. El docente ingresa "aprobar"
    - Datos: "aprobar".
    - Resultado: El BOT retorna un mensaje. "solicitud aprobada, se notificará al estudiante"   
 8. El docente ingresa "rechazar"
    - Datos: "rechazar".
    - Resultado: El BOT retorna un mensaje. "solicitud rechazada, se notificará al estudiante"

### 4 - Subir datos de la materia

*Autor*: Falvio Gabriel Miranda Velarde

*Fecha*:10/03/2022

*Prioridad*: Alta


#### 10.1 Descripción
Un *Docente* puede subir, editar o eliminar los datos de la materia (enlaces) por medio del *BOT* de telegram, para esto el docente debe enviar los respectivos enlaces e informacion correspondiente, los datos seran opcionales para cada docente, pero estos pueden ser:
    -Correos electronicos
    -Enlaces a grupo de Whatsapp o Telegram
    -Enlaces a reuniones de Zoom, Meet, etc


Esta informacion se guardara en la base de datos para futuras consultas de estudiantes

*Ingreso de datos:*

El en siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Docente #Blue

Docente -[#red]> BOT: Ingresar datos
BOT -[#blue]-> Docente : 'Ingrese Comando específico'
Docente -[#red]> BOT: Ingresa: /IngresarDatos/editar/eliminar
BOT -[#blue]-> Docente: 'Ingrese los datos que desee guardar'
database BBDD #brown

Docente  -[#red]> BOT: Ingresa: /Ingresar/editar/eliminar

BOT -[#green]-> BBDD: 'Realiza los querys'
BBDD -[#green]-> BOT: 'Devuelve resultado de la consulta'
BOT -[#blue]-> Docente: 'Notifica resultados'

@enduml

....


### 10.2 Escenarios

1. Agregar datos.
2. Editar datos.
3. Eliminar datos

### 10.3 Casos de Prueba

*Agregar datos*

Descripción: El docente puede agregar nuevos datos de la materia 

Pasos:

1. El docente Ingresa y se identifica con el BOT vía Telegram y envía el comando:
 -DOCENTE: /DatosDeMateria
 BOT: Ingrese Las siglas de su materia
2. El docente ingresa unas siglas equivocadas o de una materia en la que no es docente
 -Docente: sis-3313
 -bot:"Ingrese una materia valida"
3. El docente ingresa siglas validas 

 BOT: Ingrese comando: /Ingresar/editar/eliminar

4. El docente Ingresa el comando equivocado

- Resultado esperado: El BOT retorna un mensaje. ¨Ingrese un comando Valido¨. 

5. El doecente Ingresa el comando /Ingresar

- Resultado esperado: El BOT retorna un mensaje. ¨ingrese los datos correspondientes en un mensaje¨. 

6. El docente ingresa un espacio en blanco
- Resultado esperado: El BOT muestra un mensaje. ¨Usted debe ingresar los datos correspondientes¨.

7. El docente ingresa una imagen/video/audio
- Resultado esperado: El BOT muestra un mensaje. ¨No puede ingresar archivos¨.

8. El docente ingresa una link de Telegram
- Resultado esperado: El BOt registra el link  y consulta al docente si desea ingresar mas datos.

9. El docente ingresa el comando /Ingresar
 - Resultado esperado: El BOT retorna un mensaje. ¨ingrese los datos correspondientes en un mensaje¨. 

10. El docente ingresa un correo electronico
- Resultado esperado: El BOT registra el correo y consulta al docente si desea ingresar mas datos.

11. El docente ingresa el comando /Guardar
- Resultado esperado: El BOt registra la informacion en la base de datos.



*Editar datos*

Descripción: El docente puede editar sus datos antes guardados 

Pasos:


1. El docente Ingresa y se identifica con el BOT vía Telegram y envía el comando:
 -DOCENTE: /DatosDeMateria
 BOT: Ingrese Las siglas de su materia
2. El docente ingresa unas siglas equivocadas o de una materia en la que no es docente
 -Docente: sis-3313
 -bot:"Ingrese una materia valida"
3. El docente ingresa siglas validas 

 BOT: Ingrese comando: /Ingresar/editar/eliminar

4. El docente Ingresa el comando equivocado

- Resultado esperado: El BOT retorna un mensaje. ¨Ingrese un comando Valido¨. 

5. El docente Ingresa el comando /Editar

- Resultado esperado: El BOT muestra los datos antes guardados. 

6. El docente no ingreso datos anteriormente.
 Bot: "Usted no ingreso datos"

7. El docente ingresa un espacio en blanco
- Resultado esperado: El BOT muestra un mensaje. ¨Usted debe ingresar los datos correspondientes¨.

8. El docente ingresa una imagen/video/audio
- Resultado esperado: El BOT muestra un mensaje. ¨No puede ingresar archivos¨.

9. El docente ingresa un enlace de zoom
- Resultado esperado: El BOt registra el enlace y consulta al docente si desea ingresar mas datos.

10. El docente ingresa el comando /Ingresar
 - Resultado esperado: El BOT retorna un mensaje. ¨ingrese los datos correspondientes en un mensaje¨. 

11. El docente ingresa un numero de telefono
- Resultado esperado: El BOT registra el correo y consulta al docente si desea ingresar mas datos.

12. El docente ingresa el comando /Guardar
- Resultado esperado: El BOt registra la informacion en la base de datos.



*Eliminar datos*

Descripción: El docente puede eliminar sus datos antes guardados 

Pasos:


1. El docente Ingresa y se identifica con el BOT vía Telegram y envía el comando:
 -DOCENTE: /DatosDeMateria
 BOT: Ingrese Las siglas de su materia
2. El docente ingresa unas siglas equivocadas o de una materia en la que no es docente
 -Docente: sis-3313
 -bot:"Ingrese una materia válida"
3. El docente ingresa siglas válidas

 BOT: Ingrese comando: /Ingresar/editar/eliminar

4. El docente Ingresa el comando equivocado

- Resultado esperado: El BOT retorna un mensaje. ¨Ingrese un comando Valido¨. 

5. El docente Ingresa el comando /Eliminar

- Resultado esperado: El BOT muestra los datos antes guardados. 

6. El docente no ingreso datos anteriormente.
 Bot: "Usted no ingreso datos"

7. El docente ingreso datos anteriormente
- Resultado esperado: El BOT muestra un mensaje. ¨Confirme que desea eliminar los datos¨.

8. El docente ingresa el comando /Confirmar
- Resultado esperado: El BOT muestra un mensaje. ¨Datos eliminados¨ y procede a eliminar los datos en la base de datos.

###  11 Consulta Ayuda

*Autor*: Mauro Moya

*Fecha*:10/03/2022

*Prioridad*: Muy alta


#### 11.1 Descripción
Un *Estudiante* o *Docente* podra consultar el listado de sus alumnos por medio del *BOT* de telegram, para esto previa validacion del *Estudiante* o *Docente* y escribiendo el comando de /Ayuda, el *BOT* el bot tendra los siguientes aspectos: 

* Ayuda de comandos *Estudiante*
* Ayuda de comandos *Docente* 

El en siguiente `Diagrama de secuencia` se mostrará la secuencia de esta historia para el `Estudiante`.

[plantuml, format="png", id="estados_Consulta_horarios_estudiantes"]

....

@startuml

actor Docente #Blue

Docente -[#red]> BOT: Comando Erroneo
BOT -[#blue]-> Docente: 'Ingrese Comando específico'
Docente -[#red]> BOT: Ingresa: /Ayuda
BOT -[#green]-> BBDD: 'Realiza consulta de comandos de Docente'
BBDD -[#green]-> BOT: 'Devuelve resultado de los comandos disponibles'
BOT -[#blue]-> Docente: ' muestra las opciones de los Comandos'

@enduml

....


### 11.2 Escenarios

1. Comandos Erroneos
2. Seleccion de Ayuda Estudiante.
3. Seleccion de Ayuda Docente.

### 11.3 Casos de Prueba


Descripción: El Bot una vez validado la informacion ingresada por el *Estudiante* o *Docente* mismos que realizara la consulta al *Bot*

Pasos:

1. El *estudiante* Ingresa y se identifica con el BOT vía Telegram y envía el comando a seguir 

 -Estudiante: /Ayudame
 -BOT: Ingrese el comando /correcto o la palabra ayuda: 
 -Estudiante: /ayuda
 -BOT: Estos son los comandos que puedes usar:
 1) /ayuda-> Para solicitar ayuda con el bot
 2) /horarios-> Para solicitar los horarios del Estudiante
 *2.1) /SIGLA-PARALELO-> Para consular los horarios del curso y paralelo
 3) /notas->  Para consultar las notas
 4) /cuenta-> Para consultar las cuentas
 5) /Enviarsolicitud-> Para solicitar permiso de ausencia


2. El *docente* Ingresa y se identifica con el BOT vía Telegram y envía el comando a seguir

 -Docente: /Ayudame
 -BOT: Ingrese el comando /correcto o la palabra ayuda: 
 -Docente: /ayuda
 -BOT: Estos son los comandos que puedes usar:
 1) /ayuda-> Para solicitar ayuda con el bot
 2) /horarios-> Para solicitar los horarios del docente
 *2.1) /SIGLA-PARALELO-> Para consular los horarios del curso y paralelo
 3) /alumnos->  Para consultar la lista de alumnos
 *3.1) /SIGLA-PARALELO-> Para consultar los estudiantes del curso y paralelo
 4) /datosdemateria-> Para subir actualizar notas de las materias.
 *4.1)  /SIGLA-PARALELO-> Para registrar cambios de nota
*4.2) /Ingresar-> Ingresa nuevas notas
*4.3) /editar-> Corrige alguna nota
*4.4) /eliminar-> Elimina la nota


