openapi: '3.0.0'
info:
  title: UCB API
  description: representación de la API del proyecto de la app de la ucb
  version: 1.0.0

paths:

  /{matid}/link:

    ### Detalle de materias
    get:
      summary: Obtener el detalle de una materia(links de l clase)
      description: obtener el detalle de una materia seleccionada por el estudiante
      parameters:
        - name: matid
          in: path
          description: id de la materia
          required: true
          schema:
            type: string
      responses:
        200:
          description: detalle de materia
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/InfoDetalle'

        400:
          description: No existe la información
        403:
          description: Datos obligatorios no enviados


  /{estid}/deudasid:

    ### Deudas
    get:
      summary: Obtener deudas del estudiante
      description: Obtener deudas del usuario que inició la sesión
      parameters:
        - name: estid
          in: path
          description: id del estudiante
          required: true
          schema:
            type: string

      responses:
        200:
          description: Lista de deudas
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/InfoDeudas'

        400:
          description: No se pudo encontrar la información


  /{estid}/materiasid:

    ### Notas
    get:
      summary: Obtener notas del estudiante
      description: Obtener notas del usuario que inició la sesión
      parameters:
        - name: estid
          in: path
          description: id del estudiante
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de calificaciones
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/InfoNotas'

        400:
          description: No se pudoencontrar la información

        403:
          description: Datos obligatorios no enviados



components:
  schemas:
    InfoDetalle:
      type: object
      properties:
        Nombre:
          type: string
          example: ingeniería del software
        link:
          type: string
          example: https://neo.ucb.edu.bo/
        docente:
          type: string
          example: Pedro Perez
    InfoDeudas:
      type: object
      properties:
        Razón:
          type: string
          example: Seguro universitario 2022-1
        Monto:
          type: string
          example: 80
        Multa:
          type: string
          example: 2
    InfoNotas:
      type: object
      properties:
        Siglas:
          type: string
          example: sis111
        EC:
          type: string
          example: 60
        EF:
          type: string
          example: 70
        NOTA:
          type: string
          example: 75









